services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile 
    image: my-backend

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile 
    image: my-frontend
    ports: 
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:4000
