services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile 
    image: my-backend

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile 
    image: my-frontend
    ports: 
      - 3000:3000
    depends_on: 
      - backend
    environment:
      - BACKEND_URL=http://backend:4000
    
  prometheus:
    image: prom/prometheus:latest
    # container_name: prometheus
    ports: 
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      # TODO: move prometheus config
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    depends_on:
      - backend

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #   - 6379:6379
